# to enable spawning need restart
enabled: true
log-type: 1

# period to spawn 1 clown (seconds)
spawn-clown-timer:
  min: 50
  max: 100




# Clown Settings

# near player spawn radius (blocks)
# must be > 1
spawn-radius: 5

# has clown AI
clown-ai: true

# can clown be killed
clown-dead: false